
# $Id: makefile.end,v 12.3 2020/12/06 21:40:09 tom Exp $
# end MAKE-file for miscellaneous library routines

clean ::			; -$(RM) $(CLEAN)
distclean ::	clean
	-@$(SHELL) -c "for s in *;do if test -f \$$s/makefile; then echo .. clean \$$s; rm -f \$$s/makefile; rmdir \$$s 2>/dev/null ; fi; done; exit 0"
