#! /bin/sh
# $Id: ins_hdr,v 12.4 2023/01/16 19:52:09 tom Exp $
#
# This script is used to adjust includes for header files that reside in a
# subdirectory of /usr/include, etc.

failed() {
	echo "? $*" >&2
	exit 1
}

test $# = 0 && failed 'No INSTALL program given'
PRG="$1"
shift

test $# = 0 && failed 'No DESTINATION given'
DST=$1
shift

test $# = 0 && failed 'No SOURCEDIR given'
SOURCEDIR=$1
shift

test $# = 0 && failed 'No SOURCES given'

SED=${TMPDIR-/tmp}/sed$$
rm -f "$SED"
trap 'rm -f "$SED"; exit 1' HUP INT QUIT TERM
trap 'rm -f "$SED"; exit 0' EXIT

END=`basename "$DST"`
for SRC in "$@"
do
	echo "s,<$SRC>,<$END/$SRC>," >> "$SED"
done

for SRC in "$@"
do
	echo "installing $SRC in $DST"
	case $DST in
	/*/include/*)
		src=`basename "$SRC"`
		MAP=${TMPDIR-/tmp}/$src
		map="include/$src"
		test -f "$map" || map="$SOURCEDIR/$map"
		sed -f "$SED" "$map" > "$MAP"
		eval "$PRG" "$MAP" "$DST"
		rm -f "$MAP"
		;;
	*)
		eval "$PRG" "$SRC" "$DST"
		;;
	esac
done
