#! /bin/sh
# $Id: rem_hdr,v 12.1 1997/09/10 23:15:08 tom Exp $
#
# This script is used to remove header files that reside in a subdirectory of
# /usr/include, etc.

#DOIT=echo
DOIT=eval

if test $# = 0 ; then
	echo '? No DESTINATION given'
	exit 1
fi
DST=$1
shift

if test $# = 0 ; then
	echo '? No SOURCE given'
	exit 1
fi

for SRC in $*
do
	src=`basename $SRC`
	$DOIT rm -f $DST/$src
done
