# $Id: Makefile,v 1.2 1994/07/12 17:16:42 tom Exp $
# MAKE-file for VMS-specific/portability library routines

####### (Environment) ##########################################################
include ../td_defns.mk

####### (Standard Lists) #######################################################
CSRC	=

SOURCES	= Makefile descrip.mms $(CSRC)

OBJS	= dummy

####### (Standard Productions) #################################################
include ../td_rules.mk
