# $Id: Makefile,v 1.1 1994/07/02 15:10:36 tom Exp $
# MAKE-file for VMS-specific/portability library routines

####### (Environment) ##########################################################
include ../td_defns.mk

####### (Standard Lists) #######################################################
CSRC	=

SOURCES	= Makefile descrip.mms $(CSRC)

OBJS	=

####### (Standard Productions) #################################################
include ../td_rules.mk
