# $Id: Makefile,v 12.1 1994/07/02 18:41:08 tom Exp $
# make-file for TD_LIB common/test library

####### (Development) ##########################################################
THIS	= port2dos
include ../td_defns.mk

####### (Standard Lists) #######################################################
REF_FILES =

SCRIPTS	= \
	run_test.sh

C_SRC	=

SOURCES	= Makefile $(C_SRC) $(SCRIPTS) $(REF_FILES) $(DATA_FILES)

PROGS	=

####### (Standard Productions) #################################################
include ../td_rules.mk
