
# $Id: makefile.end,v 12.1 1997/09/09 22:04:05 tom Exp $
# end MAKE-file for miscellaneous library routines

clean ::			; -$(RM) $(CLEAN)
destroy ::			; $(DESTROY)
distclean ::	clean
	-$(RM) -f makefile
