# $Id: Makefile,v 1.2 1994/07/12 17:16:18 tom Exp $
# MAKE-file for MSDOS-specific/portability library routines

####### (Environment) ##########################################################
include ../td_defns.mk

####### (Standard Lists) #######################################################

ALL	=

CSRC	=

SOURCES	= Makefile $(CSRC)

OBJS	= dummy

####### (Standard Productions) #################################################
include ../td_rules.mk
