# $Id: Makefile,v 1.1 1994/07/02 15:08:34 tom Exp $
# MAKE-file for MSDOS-specific/portability library routines

####### (Environment) ##########################################################
include ../td_defns.mk

####### (Standard Lists) #######################################################

CSRC	=

SOURCES	= Makefile $(CSRC)

OBJS	=

####### (Standard Productions) #################################################
include ../td_rules.mk
