# $Id: Makefile,v 1.3 1995/01/28 21:10:25 tom Exp $
# MAKE-file for MSDOS-specific/portability library routines

####### (Environment) ##########################################################
include ../td_defns.mk
include ../../support/td_lib.mk

####### (Standard Lists) #######################################################

ALL	=

CSRC	=

SOURCES	= Makefile $(CSRC)

OBJS	= dummy

####### (Standard Productions) #################################################
include ../td_rules.mk
